export const SYNC_TYPE = {
    TYPE_LOGIN: "TYPE_LOGIN",
    TYPE_LEARN_TEST: "TYPE_LEARN_TEST",
    TYPE_STUDY_PLAN: "TYPE_STUDY_PLAN",
    TYPE_UPGRADE_PRO: "TYPE_UPGRADE_PRO",
    TYPE_HOME: "TYPE_HOME",
    TYPE_LANDING_PAGE: "TYPE_LANDING_PAGE",
    TYPE_THANK_YOU: "TYPE_THANK_YOU",
    TYPE_REVIEW: "TYPE_REVIEW",
    TYPE_QUESTION: "TYPE_QUESTION",
};
