const RouterApp = {
    Home: "/",
    Get_pro: "getPro",
    Topics: "topics",
    About: "about_us",
    Contacts: "contact",
    Privacy: "privacy",
    Refund_policy: "refund_policy",
    Blog: "blog",
    Teams_of_service: "teams_of_service",
    Study_Guides: "study_guides",
    Score_Calculator: "score_calculator",
    Test: "test",
    Review: "review",
    ResultTest: "result_test",
    Billing: "billing",
    Edit_policy: "editorial-policy",
    Diagnostic_test: "diagnostic_test",
    Custom_test: "custom_test",
    Final_test: "final_test",
};
export default RouterApp;
